const shopActionTypes = {
    'UPDATE_COLLECTIONS': 'UPDATE_COLLECTIONS',
    'FETCH_COLLECTIONS_START': 'FETCH_COLLECTIONS_START',
    'FETCH_COLLECTION_SUCCESS': 'FETCH_COLLECTION_SUCCESS',
    'FETCH_COLLECTION_FAIL': 'FETCH_COLLECTION_FAIL'
}

export default shopActionTypes;