export const CollectionInsightsTypes = {
    FETCH_COLLECTION_INSIGHTS: 'FETCH_COLLECTION_INSIGHTS',
    FETCH_COLLECTION_INSIGHTS_SUCCESS: 'FETCH_COLLECTION_INSIGHTS_SUCCESS',
    FETCH_COLLECTION_INSIGHTS_FAILURE: 'FETCH_COLLECTION_INSIGHTS_FAILURE'
}