export const AdminTypes = {
    FETCH_ADMIN_COLLECTION: 'FETCH_ADMIN_COLLECTION',
    FETCH_ADMIN_COLLECTION_SUCCESS: 'FETCH_ADMIN_COLLECTION_SUCCESS',
    FETCH_ADMIN_COLLECTION_FAILURE: 'FETCH_ADMIN_COLLECTION_FAILURE'
}